# Generated by Django 4.0.6 on 2022-07-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='containers',
            new_name='Signin',
        ),
        migrations.AlterModelTable(
            name='signin',
            table='signin',
        ),
    ]
